export const ApiConstants = {
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 200,
  USERNAME_MIN_LENGTH: 2,
  USERNAME_MAX_LENGTH: 64,
  FIRST_NAME_MIN_LENGTH: 2,
  FIRST_NAME_MAX_LENGTH: 100,
  LAST_NAME_MIN_LENGTH: 2,
  LAST_NAME_MAX_LENGTH: 100,
  NAME_MIN_LENGTH: 5,
  EMAIL_SUBJECT_MIN_LENGTH: 5,
  EMAIL_BODY_MIN_LENGTH: 15,
};

export const JWT_BEARER_REALM = 'Bearer';
